FROM ricc/composer-prestissimo as vendor
FROM php:7.3.5-cli-alpine

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV APP_ENV=dev

WORKDIR /var/www

# Run composer from builder image
COPY --from=vendor /usr/bin/composer /usr/bin/composer
COPY --from=vendor /tmp /root/.composer

RUN apk add --no-cache --update \
  $PHPIZE_DEPS \
  git \
  libzip-dev

RUN docker-php-ext-install zip \
  && pecl install xdebug \
  && docker-php-ext-enable xdebug

# Copy main PHP config files
COPY etc/php/php.ini /usr/local/etc/php/conf.d/php.ini

VOLUME ["/var/www"]

ENTRYPOINT ["vendor/bin/phpunit", "/var/www/tests"]